import{S as w,i as g,a as L}from"./assets/vendor-b42c18af.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const f="/goit-js-hw-12/assets/izitoast-icon-172762f2.svg",m="/goit-js-hw-12/assets/izitoast-close-b4fe742b.svg",p=new w(".gallery a",{scrollZoom:!1}),h=document.querySelector(".form"),y=document.querySelector(".gallery"),d=document.querySelector(".loader"),c=document.querySelector(".btn-load");let i,l=1;h.addEventListener("submit",F);async function b(e){if(e.trim()==="")return;const o="https://pixabay.com/api/?",s=new URLSearchParams({key:"42172991-e7a3268a8ccb87dfba8d5efbc",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:l,per_page:15}),n=o+s;try{return(await L.get(n)).data}catch(t){throw console.error("Error fetching data",t),t}}async function F(e){if(e.preventDefault(),l=1,i=document.querySelector('input[type="text"]').value.trim(),i!==""){d.classList.remove("hidden"),c.classList.remove("hidden");try{const o=await b(i);console.log("Кількість зображень:",o.totalHits),o.hits.length===0?(g.show({messageAlign:"center",message:"Sorry, there are no images matching <br> your search query. Please try again!",messageColor:"#FFFFFF",messageSize:"16px",position:"center",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",iconUrl:f,displayMode:"replace",close:!1,closeOnEscape:!0,pauseOnHover:!1,buttons:[[`<button type="button" style="background-color: transparent;"><img src=${m}></button>`,function(s,n){s.hide({transitionOut:"fadeOut"},n)}]]}),h.reset()):(y.innerHTML=v(o.hits),p.refresh(),c.classList.remove("hidden"))}catch(o){console.error("Error fetching data:",o)}finally{d.classList.add("hidden")}}}function v(e){return e.map(S).join("")}function S(e){return`<li class="gallery-card">
<a href="${e.largeImageURL}" data-lightbox="image">
    <img class="gallery-image"
    src="${e.webformatURL}" alt="${e.tags}">
</a>
<div class="details">
    <p><strong>Likes:</strong> ${e.likes}</p>
    <p><strong>Views:</strong> ${e.views}</p>
    <p><strong>Comments:</strong> ${e.comments}</p>
    <p><strong>Downloads:</strong> ${e.downloads}</p>
</div>
</li>`}c.addEventListener("click",O);async function O(){l+=1;try{const e=await b(i);e.totalHits<=l*15?(c.classList.add("hidden"),g.show({messageAlign:"center",message:"We're sorry, but you've reached the end of search results.",messageColor:"#FFFFFF",messageSize:"16px",position:"center",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",iconUrl:f,displayMode:"replace",close:!1,closeOnEscape:!0,pauseOnHover:!1,buttons:[[`<button type="button" style="background-color: transparent;"><img src=${m}></button>`,function(o,s){o.hide({transitionOut:"fadeOut"},s)}]]})):(y.insertAdjacentHTML("beforeend",v(e.hits)),p.refresh())}catch(e){console.error("Error fetching data:",e)}finally{d.style.display="none"}}const E=new IntersectionObserver((e,o)=>{e.forEach(s=>{if(s.isIntersecting){const t=s.target.getBoundingClientRect().height*2,a=window.scrollY+t;window.scrollTo({top:a,behavior:"smooth"}),o.unobserve(s.target)}})},{threshold:.5}),u=document.querySelector(".gallery-card:last-of-type");u&&E.observe(u);
//# sourceMappingURL=commonHelpers.js.map
