import{S as h,a as L,i as b}from"./assets/vendor-b42c18af.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function a(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(r){if(r.ep)return;r.ep=!0;const s=a(r);fetch(r.href,s)}})();const v="/goit-js-hw-12/assets/izitoast-icon-172762f2.svg",w="/goit-js-hw-12/assets/izitoast-close-b4fe742b.svg",d=new h(".gallery a"),o={form:document.querySelector(".form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),btnLoader:document.querySelector(".btn-load")};let u=null,n=null,f=0;const g=15;o.form.addEventListener("submit",P);o.btnLoader.addEventListener("click",S);async function S(e){e.preventDefault(),n+=1,console.log("Поточна сторінка:",n),o.loader.classList.remove("hidden");try{const t=await m(u);if(t.totalPages===0)return o.loader.classList.add("hidden"),o.btnLoader.classList.add("hidden"),i(message);const a=p(t.hits);o.gallery.insertAdjacentHTML("beforeend",a),d.refresh(),y(t);const s=o.gallery.lastElementChild.getBoundingClientRect().top;O(s)}catch(t){i(t)}o.loader.classList.add("hidden")}async function P(e){e.preventDefault(),u=document.querySelector('input[type="text"]').value.trim(),n=1,o.loader.classList.remove("hidden"),o.gallery.innerHTML="";try{const t=await m(u);if(console.log("Кількість зображень:",t.totalHits),t.totalHits===0)return o.loader.classList.add("hidden"),o.btnLoader.classList.add("hidden"),i("Sorry, there are no images matching <br/> your search query. Please try again!");const a=p(t.hits);o.gallery.innerHTML=a,d.refresh(),y(t)}catch(t){throw console.error("Error fetching data",t),t}o.loader.classList.add("hidden"),d.refresh()}async function m(e){const t="https://pixabay.com/api/?";return(await L.get(t,{params:{key:"42172991-e7a3268a8ccb87dfba8d5efbc",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,currentPage:n,per_page:g}})).data}function p(e){return e.map(q).join("")}function q(e){return`<li class="gallery-card">
<a href="${e.largeImageURL}" data-lightbox="image">
    <img class="gallery-image"
    src="${e.webformatURL}" alt="${e.tags}">
</a>
<div class="details">
    <p><strong>Likes:</strong> ${e.likes}</p>
    <p><strong>Views:</strong> ${e.views}</p>
    <p><strong>Comments:</strong> ${e.comments}</p>
    <p><strong>Downloads:</strong> ${e.downloads}</p>
</div>
</li>`}function i(e){b.error({message:e,messageAlign:"center",position:"center",messageColor:"#ffffff",messageSize:"16px",backgroundColor:"#ef4040",progressBarColor:"#B51B1B",iconColor:"#ffffff",iconUrl:v,timeout:5e3,displayMode:"replace",close:!1,closeOnEscape:!0,buttons:[[`<button type="button" style="background-color: transparent;"><img src=${w}></button>`,function(t,a){t.hide({transitionOut:"fadeOut"},a)}]]})}function y(e){f=Math.ceil(e.totalHits/g),f===n?(o.btnLoader.classList.add("hidden"),i("We're sorry, but you've reached the end of search results.")):o.btnLoader.classList.remove("hidden")}function O(e){window.scrollBy({top:e,left:0,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
