import{S as h,i as y}from"./assets/vendor-7659544d.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const b="/goit-js-hw-12/assets/izitoast-icon-172762f2.svg",L="/goit-js-hw-12/assets/izitoast-close-b4fe742b.svg",g=new h(".gallery a",{scrollZoom:!1}),f=document.querySelector(".form"),c=document.querySelector(".gallery"),l=document.querySelector(".loader"),u=document.querySelector(".btn-load");let i,d=1;f.addEventListener("submit",v);function m(e){const o="https://pixabay.com/api/?",n=new URLSearchParams({key:"42172991-e7a3268a8ccb87dfba8d5efbc",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:d,per_page:15}),s=o+n;return fetch(s).then(t=>t.json())}function v(e){e.preventDefault(),d=1,i=document.querySelector('input[type="text"]').value.trim(),i!==""&&(l.classList.remove("hidden"),u.classList.remove("hidden"),m(i).then(o=>{o.hits.length===0?(y.show({messageAlign:"center",message:"Sorry, there are no images matching <br> your search query. Please try again!",messageColor:"#FFFFFF",messageSize:"16px",position:"center",backgroundColor:"#EF4040",progressBarColor:"#B51B1B",iconUrl:b,displayMode:"replace",close:!1,closeOnEscape:!0,pauseOnHover:!1,buttons:[[`<button type="button" style="background-color: transparent;"><img src=${L}></button>`,function(n,s){n.hide({transitionOut:"fadeOut"},s)}]]}),f.reset()):(c.innerHTML=p(o.hits),g.refresh(),u.classList.remove("hidden"))}).catch(o=>console.error("Error fetching data:",o)).finally(()=>{l.classList.add("hidden")}))}function p(e){return e.map(S).join("")}function S(e){return`<li class="gallery-card">
<a href="${e.largeImageURL}" data-lightbox="image">
    <img class="gallery-image"
    src="${e.webformatURL}" alt="${e.tags}">
</a>
<div class="details">
    <p><strong>Likes:</strong> ${e.likes}</p>
    <p><strong>Views:</strong> ${e.views}</p>
    <p><strong>Comments:</strong> ${e.comments}</p>
    <p><strong>Downloads:</strong> ${e.downloads}</p>
</div>
</li>`}u.addEventListener("click",w);function w(){d+=1,m(i).then(e=>{e.hits.length===0?c.innerHTML="<p>Sorry, there are no images matching your search query. Please try again!</p>":(c.insertAdjacentHTML("beforeend",p(e.hits)),g.refresh())}).catch(e=>console.error("Error fetching data:",e)).finally(()=>{l.style.display="none"})}
//# sourceMappingURL=commonHelpers.js.map
